version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Install make
          command: apt-get install make

      - run:
          name: Run all tests
          command: make test
