version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout
      - run: apt-get update
      - run: apt-get install make git neovim
      - run: make deps
      - run: make test
